apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: argo-east-vpc
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 192.168.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: aws-provider-east